In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/fitness_calories_dataset.csv")
df

,duration_min,heart_rate_avg,weight_kg,workout_type,age,calories_burned
0,11.8,108,49.9,running,26,239.77
1,53.7,167,84.2,swimming,63,623.81
2,74.2,178,53.3,swimming,27,808.46
3,34.5,104,105.4,swimming,40,488.59
4,72.0,161,92.6,swimming,47,804.20
...,...,...,...,...,...,...
2495,81.5,173,60.7,running,46,748.66
2496,44.5,160,92.8,yoga,30,365.01
2497,15.2,173,77.1,yoga,42,312.75
2498,23.0,83,82.1,running,42,308.50
2499,59.6,91,109.8,cycling,20,591.32

In [2]:
# check shape of dataset
df.shape

(2500, 6)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   duration_min     2500 non-null   float64
 1   heart_rate_avg   2500 non-null   int64
 2   weight_kg        2500 non-null   float64
 3   workout_type     2500 non-null   str
 4   age              2500 non-null   int64
 5   calories_burned  2500 non-null   float64
dtypes: float64(3), int64(2), str(1)
memory usage: 133.8 KB

In [4]:
# check summary statistics
df.describe()

       duration_min  heart_rate_avg    weight_kg          age  calories_burned
count   2500.000000     2500.000000  2500.000000  2500.000000      2500.000000
mean      50.441160      129.708400    77.922040    39.562800       502.920632
std       23.247652       29.005929    18.963779    14.077092       159.585623
min       10.000000       80.000000    45.000000    16.000000       167.930000
25%       30.175000      104.000000    61.500000    27.000000       374.052500
50%       50.600000      130.000000    78.400000    39.000000       489.275000
75%       70.500000      155.000000    94.300000    52.000000       625.672500
max       90.000000      179.000000   110.000000    64.000000       976.060000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# check for missing values
df.isnull().sum()

duration_min       0
heart_rate_avg     0
weight_kg          0
workout_type       0
age                0
calories_burned    0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['workout_type']=le.fit_transform(df['workout_type'])

In [8]:
## KNN REGRESSION
X=df.drop(['calories_burned'],axis=1)
y=df['calories_burned']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## KNN REGRESSOR
from sklearn.neighbors import KNeighborsRegressor
regressor=KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.6053116074087057