In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/fruit_quality_dataset.csv")
df

,weight_g,diameter_cm,sugar_content_brix,color,days_since_harvest,is_fresh
0,200.1,5.2,13.5,yellow,3,1
1,244.3,11.7,10.4,green,2,1
2,275.7,3.0,11.0,red,7,1
3,168.7,7.8,9.4,green,12,1
4,229.4,3.7,5.3,green,13,0
...,...,...,...,...,...,...
2495,334.3,7.2,9.6,green,9,0
2496,206.5,8.6,7.2,orange,16,0
2497,362.7,7.9,18.3,red,11,0
2498,92.6,11.2,14.8,red,4,1
2499,289.9,9.1,16.9,green,17,0

In [2]:
# check shape of dataset
df.shape

(2500, 6)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   weight_g            2500 non-null   float64
 1   diameter_cm         2500 non-null   float64
 2   sugar_content_brix  2500 non-null   float64
 3   color               2500 non-null   str
 4   days_since_harvest  2500 non-null   int64
 5   is_fresh            2500 non-null   int64
dtypes: float64(3), int64(2), str(1)
memory usage: 129.0 KB

In [4]:
# check summary statistics
df.describe()

,weight_g,diameter_cm,sugar_content_brix,days_since_harvest,is_fresh
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.0000
mean,223.596080,7.491560,12.492280,9.552000,0.5000
std,101.825772,2.634254,4.334194,5.728283,0.5001
min,50.700000,3.000000,5.000000,0.000000,0.0000
25%,133.875000,5.200000,8.775000,5.000000,0.0000
50%,219.650000,7.500000,12.500000,10.000000,0.5000
75%,315.300000,9.800000,16.200000,14.000000,1.0000
max,399.800000,12.000000,20.000000,19.000000,1.0000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# check for missing values
df.isnull().sum()

weight_g              0
diameter_cm           0
sugar_content_brix    0
color                 0
days_since_harvest    0
is_fresh              0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['color']=le.fit_transform(df['color'])

In [8]:
X=df.drop(['is_fresh'],axis=1)
y=df['is_fresh']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
##KNN CLASSIFIER
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.714