In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/laptop_price_dataset.csv")
df

,ram_gb,storage_gb,screen_size_in,cpu_cores,brand,has_ssd,price
0,32,512,13.6,9,dell,1,81910.69
1,32,512,11.4,3,hp,0,72714.83
2,32,128,13.2,14,lenovo,1,82345.35
3,32,512,15.6,5,dell,1,78811.16
4,32,1024,11.6,10,dell,0,91258.45
...,...,...,...,...,...,...,...
2495,8,256,11.1,4,hp,0,40683.29
2496,32,128,15.5,6,dell,0,64264.22
2497,16,1024,14.0,8,apple,1,105595.82
2498,8,256,16.9,3,hp,0,44168.81
2499,16,128,16.6,7,hp,1,54387.94

In [2]:
# check shape of dataset
df.shape

(2500, 7)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ram_gb          2500 non-null   int64
 1   storage_gb      2500 non-null   int64
 2   screen_size_in  2500 non-null   float64
 3   cpu_cores       2500 non-null   int64
 4   brand           2500 non-null   str
 5   has_ssd         2500 non-null   int64
 6   price           2500 non-null   float64
dtypes: float64(2), int64(4), str(1)
memory usage: 146.6 KB

In [4]:
# check summary statistics
df.describe()

,ram_gb,storage_gb,screen_size_in,cpu_cores,has_ssd,price
count,2500.000000,2500.000000,2500.00000,2500.000000,2500.000000,2500.000000
mean,24.508800,478.412800,13.93596,9.076000,0.488800,75993.713068
std,21.688552,336.411402,1.73287,4.379714,0.499975,23656.282721
min,4.000000,128.000000,11.00000,2.000000,0.000000,30028.370000
25%,8.000000,256.000000,12.40000,5.000000,0.000000,57900.302500
50%,16.000000,512.000000,13.90000,9.000000,0.000000,71552.565000
75%,32.000000,512.000000,15.40000,13.000000,1.000000,92184.095000
max,64.000000,1024.000000,17.00000,16.000000,1.000000,157143.880000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# check for missing values
df.isnull().sum()

ram_gb            0
storage_gb        0
screen_size_in    0
cpu_cores         0
brand             0
has_ssd           0
price             0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['brand']=le.fit_transform(df['brand'])

In [8]:
## X AND Y SPLIT
X=df.drop(['price'],axis=1)
y=df['price']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## LINEAR REGRESSION
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(X_train,y_train)
y_pred=regression.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.933455300753933