In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/loan_approval_dataset.csv")
df

,applicant_income,loan_amount,credit_score,employment_type,years_employed,has_default,approved
0,136730,1708143,449,salaried,1,0,0
1,105173,923252,533,salaried,2,1,0
2,185562,1337025,363,salaried,10,1,1
3,54148,422780,550,self_employed,0,0,0
4,34705,1292787,803,salaried,0,0,0
...,...,...,...,...,...,...,...
2495,69943,1826161,797,salaried,11,1,0
2496,136939,578593,440,salaried,8,0,1
2497,79776,1561338,500,salaried,1,0,0
2498,146914,1434876,572,salaried,15,0,1
2499,113283,758123,857,self_employed,8,1,1

In [2]:
# check shape of dataset
df.shape

(2500, 7)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   applicant_income  2500 non-null   int64
 1   loan_amount       2500 non-null   int64
 2   credit_score      2500 non-null   int64
 3   employment_type   2500 non-null   str
 4   years_employed    2500 non-null   int64
 5   has_default       2500 non-null   int64
 6   approved          2500 non-null   int64
dtypes: int64(6), str(1)
memory usage: 159.6 KB

In [4]:
# check summary statistics
df.describe()

,applicant_income,loan_amount,credit_score,years_employed,has_default,approved
count,2500.000000,2.500000e+03,2500.000000,2500.000000,2500.00000,2500.0000
mean,106466.544000,1.010706e+06,599.335200,14.507600,0.52280,0.5000
std,53969.530176,5.621405e+05,172.095976,8.636653,0.49958,0.5001
min,15313.000000,5.031900e+04,300.000000,0.000000,0.00000,0.0000
25%,59817.000000,5.271400e+05,452.000000,7.000000,0.00000,0.0000
50%,105227.000000,1.010523e+06,603.000000,15.000000,1.00000,0.5000
75%,153870.500000,1.505674e+06,750.250000,22.000000,1.00000,1.0000
max,199981.000000,1.999550e+06,899.000000,29.000000,1.00000,1.0000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# check for missing values
df.isnull().sum()

applicant_income    0
loan_amount         0
credit_score        0
employment_type     0
years_employed      0
has_default         0
approved            0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['employment_type']=le.fit_transform(df['employment_type'])

In [8]:
###LOGISTIC REGRESSION
X=df.drop(['approved'],axis=1)
y=df['approved']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression()
regressor.fit(X,y)
y_pred=regressor.predict(X)

In [11]:
y_pred = regressor.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.788