In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/crop_yield_dataset.csv")
df

,rainfall_mm,temperature_c,soil_type,fertilizer_kg,area_hectare,yield_tons
0,201.9,27.6,silty,90.0,15.21,8.38
1,542.2,11.9,sandy,97.2,12.44,6.15
2,886.3,13.0,loamy,64.9,14.78,13.79
3,1563.2,39.6,sandy,125.4,10.20,12.01
4,1861.3,12.4,clay,9.9,9.66,11.34
...,...,...,...,...,...,...
2495,256.0,22.0,sandy,18.7,12.59,8.70
2496,1019.8,10.4,sandy,10.8,4.66,4.14
2497,635.7,24.1,clay,11.5,9.12,8.42
2498,433.8,21.7,loamy,77.0,7.38,6.25
2499,1305.8,31.1,loamy,106.1,2.00,11.03

In [2]:
# check shape of dataset
df.shape

(2500, 6)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   rainfall_mm    2500 non-null   float64
 1   temperature_c  2500 non-null   float64
 2   soil_type      2500 non-null   str
 3   fertilizer_kg  2500 non-null   float64
 4   area_hectare   2500 non-null   float64
 5   yield_tons     2500 non-null   float64
dtypes: float64(5), str(1)
memory usage: 128.9 KB

In [4]:
# check summary statistics
df.describe()

       rainfall_mm  temperature_c  fertilizer_kg  area_hectare   yield_tons
count  2500.000000    2500.000000    2500.000000   2500.000000  2500.000000
mean   1122.734600      24.840200     101.312760     10.228156    11.456800
std     510.362107       8.746432      57.916016      5.688853     3.364249
min     201.400000      10.000000       0.000000      0.520000     0.720000
25%     696.600000      17.100000      52.075000      5.260000     9.087500
50%    1107.900000      24.900000     101.900000     10.205000    11.420000
75%    1571.150000      32.400000     150.850000     15.235000    13.710000
max    1997.700000      40.000000     200.000000     19.990000    21.640000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# check for missing values
df.isnull().sum()

rainfall_mm      0
temperature_c    0
soil_type        0
fertilizer_kg    0
area_hectare     0
yield_tons       0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['soil_type']=le.fit_transform(df['soil_type'])

In [8]:
## RANDOM FOREST REGRESSOR
X=df.drop(['yield_tons'],axis=1)
y=df['yield_tons']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## RANDOM FOREST REGRESSOR
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.7398405510397167