In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/email_spam_dataset.csv")
df

,num_links,num_words,has_attachment,sender_domain,exclamation_count,is_spam
0,8,39,1,yahoo,14,1
1,18,203,1,yahoo,12,1
2,6,377,1,yahoo,12,1
3,11,282,0,unknown,12,1
4,5,77,1,yahoo,1,0
...,...,...,...,...,...,...
2495,3,215,0,gmail,7,0
2496,7,148,0,yahoo,1,0
2497,12,35,1,yahoo,10,1
2498,11,446,0,gmail,5,0
2499,17,156,0,yahoo,11,1

In [2]:
# check shape of dataset
df.shape

(2500, 6)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   num_links          2500 non-null   int64
 1   num_words          2500 non-null   int64
 2   has_attachment     2500 non-null   int64
 3   sender_domain      2500 non-null   str
 4   exclamation_count  2500 non-null   int64
 5   is_spam            2500 non-null   int64
dtypes: int64(5), str(1)
memory usage: 131.3 KB

In [4]:
# check summary statistics
df.describe()

         num_links    num_words  has_attachment  exclamation_count    is_spam
count  2500.000000  2500.000000     2500.000000        2500.000000  2500.0000
mean      9.538000   254.242400        0.492000           7.068000     0.5000
std       5.726506   140.670855        0.500036           4.307807     0.5001
min       0.000000    10.000000        0.000000           0.000000     0.0000
25%       5.000000   130.000000        0.000000           3.000000     0.0000
50%       9.000000   255.000000        0.000000           7.000000     0.5000
75%      15.000000   376.000000        1.000000          11.000000     1.0000
max      19.000000   499.000000        1.000000          14.000000     1.0000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(5)

In [6]:
# check for missing values
df.isnull().sum()

num_links            0
num_words            0
has_attachment       0
sender_domain        0
exclamation_count    0
is_spam              0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sender_domain']=le.fit_transform(df['sender_domain'])

In [8]:
X=df.drop(['is_spam'],axis=1)
y=df['is_spam']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
##SVM CLASSIFIER (SVC)
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.744