In [1]:
import warnings
warnings.filterwarnings("ignore")
# load the data
import pandas as pd
df=pd.read_csv("../../data/dataset_anshika/delivery_time_dataset.csv")
df

,distance_km,num_packages,traffic_level,vehicle_type,driver_experience_years,delivery_time_min
0,13.7,3,4,bike,15,60.26
1,31.9,5,2,bike,0,93.77
2,13.4,6,3,car,5,60.37
3,36.3,9,1,car,14,108.43
4,17.5,9,1,car,11,70.61
...,...,...,...,...,...,...
2495,49.7,19,2,bike,9,164.98
2496,4.7,18,5,bike,10,54.34
2497,36.8,8,4,bike,16,115.41
2498,12.8,12,3,bike,11,59.60
2499,45.0,19,1,bike,13,144.94

In [2]:
# check shape of dataset
df.shape

(2500, 6)

In [3]:
# check column dtypes and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   distance_km              2500 non-null   float64
 1   num_packages             2500 non-null   int64
 2   traffic_level            2500 non-null   int64
 3   vehicle_type             2500 non-null   str
 4   driver_experience_years  2500 non-null   int64
 5   delivery_time_min        2500 non-null   float64
dtypes: float64(2), int64(3), str(1)
memory usage: 126.6 KB

In [4]:
# check summary statistics
df.describe()

,distance_km,num_packages,traffic_level,driver_experience_years,delivery_time_min
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,25.711480,10.118400,3.029200,9.488800,95.597160
std,14.064614,5.390065,1.409518,5.725224,36.950116
min,1.000000,1.000000,1.000000,0.000000,5.000000
25%,13.900000,6.000000,2.000000,5.000000,66.085000
50%,25.500000,10.000000,3.000000,10.000000,95.630000
75%,37.900000,15.000000,4.000000,14.000000,125.620000
max,50.000000,19.000000,5.000000,19.000000,193.360000

In [5]:
# check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [6]:
# check for missing values
df.isnull().sum()

distance_km                0
num_packages               0
traffic_level              0
vehicle_type               0
driver_experience_years    0
delivery_time_min          0
dtype: int64

In [7]:
# encode the categorical column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['vehicle_type']=le.fit_transform(df['vehicle_type'])

In [8]:
## SVM REGRESSION
X=df.drop(['delivery_time_min'],axis=1)
y=df['delivery_time_min']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## SVM REGRESSOR (SVR)
from sklearn.svm import SVR
regressor=SVR()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.949105916036113