In [12]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("movie_revenue_dataset.csv")
df

,budget_million,runtime_min,genre,num_screens,marketing_spend_million,box_office_revenue_million
0,220.8,97,action,2384,58.3,554.99
1,15.7,77,comedy,2883,67.5,190.74
2,133.5,159,scifi,3132,81.8,439.05
3,298.6,91,comedy,800,4.9,548.97
4,157.0,137,scifi,3589,91.6,507.09
...,...,...,...,...,...,...
2495,164.0,170,scifi,1206,29.6,426.40
2496,279.3,124,action,2303,96.1,684.45
2497,73.7,168,scifi,2805,61.7,298.74
2498,200.8,153,comedy,3902,10.3,492.44
2499,18.8,130,comedy,3732,59.0,190.68

In [13]:
df.shape

(2500, 6)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   budget_million              2500 non-null   float64
 1   runtime_min                 2500 non-null   int64
 2   genre                       2500 non-null   str
 3   num_screens                 2500 non-null   int64
 4   marketing_spend_million     2500 non-null   float64
 5   box_office_revenue_million  2500 non-null   float64
dtypes: float64(3), int64(2), str(1)
memory usage: 131.1 KB

In [15]:
df.describe()

,budget_million,runtime_min,num_screens,marketing_spend_million,box_office_revenue_million
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,149.847760,127.289200,2481.490000,50.512360,397.930472
std,87.680642,30.214346,1139.431636,28.764916,165.214878
min,1.000000,75.000000,500.000000,0.500000,0.500000
25%,72.500000,102.000000,1497.000000,26.600000,257.332500
50%,150.700000,128.000000,2482.000000,49.900000,396.735000
75%,226.200000,153.000000,3473.250000,76.300000,536.102500
max,299.700000,179.000000,4498.000000,99.900000,761.070000

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.isnull().sum()

budget_million                0
runtime_min                   0
genre                         0
num_screens                   0
marketing_spend_million       0
box_office_revenue_million    0
dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['genre']=le.fit_transform(df['genre'])

In [19]:
## SVM REGRESSION
X=df.drop(['box_office_revenue_million'],axis=1)
y=df['box_office_revenue_million']

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [22]:
## SVM REGRESSOR (SVR)
from sklearn.svm import SVR
regressor=SVR()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [23]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.7849815677735632