In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("used_car_dataset.csv")
df

,car_age_years,mileage_km,engine_size_l,num_previous_owners,fuel_type,had_accident,service_history_score,resale_price,good_deal
0,12,173510,2.2,3,petrol,0,2,7002.41,0
1,14,189691,1.7,3,diesel,0,4,6678.08,0
2,0,76772,1.5,2,petrol,1,6,27564.35,1
3,14,84476,3.2,1,electric,0,6,20784.01,0
4,14,139648,2.0,4,diesel,0,10,11300.71,0
...,...,...,...,...,...,...,...,...,...
2995,5,153496,2.7,4,petrol,1,8,13281.06,0
2996,1,119496,3.9,4,electric,0,8,36393.76,1
2997,14,81724,2.4,1,diesel,0,4,13338.75,0
2998,6,79458,1.8,1,petrol,1,7,22064.82,1
2999,2,117557,2.2,3,petrol,1,2,19395.20,0

In [2]:
df.shape

(3000, 9)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   car_age_years          3000 non-null   int64
 1   mileage_km             3000 non-null   int64
 2   engine_size_l          3000 non-null   float64
 3   num_previous_owners    3000 non-null   int64
 4   fuel_type              3000 non-null   object
 5   had_accident           3000 non-null   int64
 6   service_history_score  3000 non-null   int64
 7   resale_price           3000 non-null   float64
 8   good_deal              3000 non-null   int64
dtypes: float64(2), int64(6), object(1)
memory usage: 211.1+ KB

In [4]:
df.describe()

,car_age_years,mileage_km,engine_size_l,num_previous_owners,had_accident,service_history_score,resale_price,good_deal
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,7.046333,98939.538000,2.509500,2.496000,0.497667,5.562667,19943.182860,0.500000
std,4.291580,57744.617756,0.870149,1.118511,0.500078,2.850868,7960.699208,0.500083
min,0.000000,31.000000,1.000000,1.000000,0.000000,1.000000,500.000000,0.000000
25%,3.000000,48859.500000,1.800000,1.750000,0.000000,3.000000,14188.562500,0.000000
50%,7.000000,98773.000000,2.500000,2.000000,0.000000,6.000000,19713.610000,0.500000
75%,11.000000,149428.750000,3.300000,4.000000,1.000000,8.000000,25574.517500,1.000000
max,14.000000,199852.000000,4.000000,4.000000,1.000000,10.000000,47430.170000,1.000000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

car_age_years            0
mileage_km               0
engine_size_l            0
num_previous_owners      0
fuel_type                0
had_accident             0
service_history_score    0
resale_price             0
good_deal                0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['fuel_type']=le.fit_transform(df['fuel_type'])

In [8]:
## X AND Y SPLIT
X=df.drop(['resale_price'],axis=1)
y=df['resale_price']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## LINEAR REGRESSION
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(X_train,y_train)
y_pred=regression.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8549690058553255

In [12]:
## RANDOM FOREST REGRESSOR
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [13]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.9338360237794039

In [14]:
###LOGISTIC REGRESSION
X=df.drop(['good_deal'],axis=1)
y=df['good_deal']

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.linear_model import LogisticRegression
regressor=LogisticRegression()
regressor.fit(X,y)
y_pred=regressor.predict(X)

In [17]:
y_pred = regressor.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.86

In [18]:
##RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=1000,random_state=42)
clf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1000, random_state=42)

In [19]:
y_pred = regressor.predict(X_test)
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.4391025641025641

In [20]:
##DECISION TREE REGRESSOR
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42)
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
y_pred = model.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7733333333333333

In [23]:
## random tree regressor
X=df.drop(['resale_price'],axis=1)
y=df['resale_price']

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [25]:
from sklearn.tree import DecisionTreeRegressor

regressor= DecisionTreeRegressor(random_state=42)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [26]:
y_pred = regressor.predict(X_test)

In [27]:
from sklearn.metrics import r2_score
r2= r2_score(y_test, y_pred)
print("r2:", r2)

r2: 0.8495580266462903