In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("../data/wine_quality_dataset.csv")
df

      acidity  sugar_content  alcohol_pct wine_type  ph_level  is_good
0        7.52           3.10         14.1       red      3.74        1
1        4.79           9.25         15.0       red      3.23        1
2        4.69          10.39          9.4       red      3.56        0
3        3.49           4.23         11.6      rose      3.97        1
4        7.54           9.15         12.8     white      3.23        0
...       ...            ...          ...       ...       ...      ...
2495     4.95          11.63         11.0       red      3.10        1
2496     8.48          13.05         11.4       red      3.05        0
2497     7.65          13.72          9.3     white      3.89        0
2498     3.36           4.09          9.3     white      3.20        1
2499     4.50          12.74         11.9     white      3.36        1

[2500 rows x 6 columns]

In [2]:
df.shape

(2500, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   acidity        2500 non-null   float64
 1   sugar_content  2500 non-null   float64
 2   alcohol_pct    2500 non-null   float64
 3   wine_type      2500 non-null   str
 4   ph_level       2500 non-null   float64
 5   is_good        2500 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 127.1 KB

In [4]:
df.describe()

           acidity  sugar_content  alcohol_pct     ph_level    is_good
count  2500.000000    2500.000000  2500.000000  2500.000000  2500.0000
mean      5.996252       7.852172    11.519680     3.410480     0.5000
std       1.710577       4.177274     2.021752     0.347951     0.5001
min       3.000000       0.520000     8.000000     2.800000     0.0000
25%       4.550000       4.170000     9.800000     3.110000     0.0000
50%       5.970000       7.935000    11.600000     3.410000     0.5000
75%       7.470000      11.430000    13.200000     3.720000     1.0000
max       9.000000      15.000000    15.000000     4.000000     1.0000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

acidity          0
sugar_content    0
alcohol_pct      0
wine_type        0
ph_level         0
is_good          0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['wine_type']=le.fit_transform(df['wine_type'])

In [8]:
X=df.drop(['is_good'],axis=1)
y=df['is_good']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
##KNN CLASSIFIER
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.65