In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("../data/electricity_bill_dataset.csv")
df

,units_consumed,household_size,ac_units,area_type,season_factor,bill_amount
0,1189.1,7,4,semiurban,1.49,10479.92
1,102.8,3,3,semiurban,1.10,2015.41
2,404.0,1,4,urban,1.32,4475.01
3,935.7,5,3,rural,1.12,8207.55
4,1112.2,4,2,rural,1.39,9085.33
...,...,...,...,...,...,...
2495,1083.0,6,3,urban,1.49,9550.43
2496,885.9,6,2,rural,0.98,7573.62
2497,1164.7,1,4,urban,1.06,10262.06
2498,550.8,1,1,urban,0.99,4846.13
2499,565.3,6,2,semiurban,1.44,5368.29

In [2]:
df.shape

(2500, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   units_consumed  2500 non-null   float64
 1   household_size  2500 non-null   int64
 2   ac_units        2500 non-null   int64
 3   area_type       2500 non-null   str
 4   season_factor   2500 non-null   float64
 5   bill_amount     2500 non-null   float64
dtypes: float64(3), int64(2), str(1)
memory usage: 132.6 KB

In [4]:
df.describe()

,units_consumed,household_size,ac_units,season_factor,bill_amount
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,620.728360,4.010400,2.027600,1.153816,5626.057892
std,332.655184,2.009355,1.406709,0.203172,2536.297899
min,50.400000,1.000000,0.000000,0.800000,587.830000
25%,334.450000,2.000000,1.000000,0.980000,3504.382500
50%,610.050000,4.000000,2.000000,1.150000,5595.655000
75%,908.550000,6.000000,3.000000,1.332500,7817.077500
max,1199.800000,7.000000,4.000000,1.500000,10939.800000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

units_consumed    0
household_size    0
ac_units          0
area_type         0
season_factor     0
bill_amount       0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['area_type']=le.fit_transform(df['area_type'])

In [8]:
## SVM REGRESSION
X=df.drop(['bill_amount'],axis=1)
y=df['bill_amount']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## SVM REGRESSOR (SVR)
from sklearn.svm import SVR
regressor=SVR()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.30661425945533494