In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("movie_genre_hit_dataset.csv")
df

,budget_million,runtime_min,genre,critic_score,lead_actor_popularity,is_hit
0,233.1,153,scifi,75.2,57.0,1
1,89.3,95,scifi,77.4,62.1,1
2,22.1,159,horror,5.1,48.4,0
3,1.7,87,drama,38.1,72.2,0
4,11.7,100,action,42.3,61.0,0
...,...,...,...,...,...,...
2495,268.4,86,action,20.1,88.6,1
2496,79.5,147,drama,52.9,3.4,0
2497,264.0,84,comedy,49.7,40.5,1
2498,145.5,113,comedy,94.5,23.9,1
2499,5.5,97,scifi,61.2,92.5,1

In [2]:
df.shape

(2500, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   budget_million         2500 non-null   float64
 1   runtime_min            2500 non-null   int64
 2   genre                  2500 non-null   str
 3   critic_score           2500 non-null   float64
 4   lead_actor_popularity  2500 non-null   float64
 5   is_hit                 2500 non-null   int64
dtypes: float64(3), int64(2), str(1)
memory usage: 131.1 KB

In [4]:
df.describe()

,budget_million,runtime_min,critic_score,lead_actor_popularity,is_hit
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.0000
mean,151.382000,128.273200,49.479160,50.965360,0.5000
std,85.381188,30.374694,28.862772,29.226861,0.5001
min,1.200000,75.000000,0.000000,0.000000,0.0000
25%,78.675000,102.000000,24.175000,25.000000,0.0000
50%,148.750000,129.000000,49.850000,52.100000,0.5000
75%,225.500000,155.000000,74.250000,76.900000,1.0000
max,300.000000,179.000000,100.000000,100.000000,1.0000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

budget_million           0
runtime_min              0
genre                    0
critic_score             0
lead_actor_popularity    0
is_hit                   0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['genre']=le.fit_transform(df['genre'])

In [8]:
X=df.drop(['is_hit'],axis=1)
y=df['is_hit']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
##SVM CLASSIFIER (SVC)
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.758