In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("loan_creditworthiness_dataset.csv")
df

,monthly_income,credit_score,job_type,existing_loans,savings_ratio,creditworthy
0,98514,563,retired,0,0.43,1
1,46922,417,business,4,0.30,0
2,74262,682,salaried,3,0.51,1
3,29096,434,business,3,0.44,0
4,142961,658,student,1,0.07,1
...,...,...,...,...,...,...
1995,84541,352,business,2,0.36,0
1996,57046,586,salaried,1,0.43,1
1997,12033,672,business,1,0.05,0
1998,23273,880,student,2,0.04,0
1999,148215,327,student,1,0.10,0

In [2]:
df.shape

(2000, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   monthly_income  2000 non-null   int64
 1   credit_score    2000 non-null   int64
 2   job_type        2000 non-null   str
 3   existing_loans  2000 non-null   int64
 4   savings_ratio   2000 non-null   float64
 5   creditworthy    2000 non-null   int64
dtypes: float64(1), int64(4), str(1)
memory usage: 108.9 KB

In [4]:
df.describe()

,monthly_income,credit_score,existing_loans,savings_ratio,creditworthy
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,77789.785000,602.734500,2.020500,0.304500,0.500000
std,41483.712852,173.908275,1.422706,0.173356,0.500125
min,8136.000000,300.000000,0.000000,0.000000,0.000000
25%,40422.500000,451.000000,1.000000,0.150000,0.000000
50%,77849.000000,603.000000,2.000000,0.310000,0.500000
75%,112805.250000,757.000000,3.000000,0.460000,1.000000
max,149826.000000,899.000000,4.000000,0.600000,1.000000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

monthly_income    0
credit_score      0
job_type          0
existing_loans    0
savings_ratio     0
creditworthy      0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['job_type']=le.fit_transform(df['job_type'])

In [8]:
X=df.drop(['creditworthy'],axis=1)
y=df['creditworthy']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
##KNN CLASSIFIER
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.905