In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("concrete_strength_dataset.csv")
df

,cement_kg,water_kg,age_days,mix_type,aggregate_kg,compressive_strength
0,367.5,238.4,166,highperf,801.6,60.15
1,288.3,224.0,159,highperf,756.6,54.87
2,204.8,138.9,106,standard,1004.7,44.91
3,248.8,167.2,303,standard,900.2,46.60
4,190.1,236.2,308,standard,845.1,42.55
...,...,...,...,...,...,...
2495,388.1,141.7,77,lightweight,1143.8,52.38
2496,410.2,219.8,28,standard,755.5,45.29
2497,375.6,104.2,284,lightweight,1071.7,57.90
2498,205.2,191.1,71,standard,1097.4,38.61
2499,237.5,240.8,119,standard,1071.5,40.54

In [2]:
df.shape

(2500, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cement_kg             2500 non-null   float64
 1   water_kg              2500 non-null   float64
 2   age_days              2500 non-null   int64
 3   mix_type              2500 non-null   str
 4   aggregate_kg          2500 non-null   float64
 5   compressive_strength  2500 non-null   float64
dtypes: float64(4), int64(1), str(1)
memory usage: 138.3 KB

In [4]:
df.describe()

,cement_kg,water_kg,age_days,aggregate_kg,compressive_strength
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000
mean,303.021920,173.897440,181.830000,948.322120,51.055972
std,114.427566,43.129313,103.447146,142.501821,11.415849
min,100.100000,100.000000,1.000000,700.100000,19.430000
25%,205.025000,136.150000,93.000000,825.400000,42.500000
50%,304.050000,175.000000,182.500000,947.700000,51.020000
75%,401.425000,209.500000,269.000000,1070.125000,59.302500
max,499.800000,250.000000,364.000000,1200.000000,83.440000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

cement_kg               0
water_kg                0
age_days                0
mix_type                0
aggregate_kg            0
compressive_strength    0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['mix_type']=le.fit_transform(df['mix_type'])

In [8]:
## RANDOM FOREST REGRESSOR
X=df.drop(['compressive_strength'],axis=1)
y=df['compressive_strength']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## RANDOM FOREST REGRESSOR
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.9057540843286098