In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
df=pd.read_csv("used_bike_price_dataset.csv")
df

      age_years  km_driven  engine_cc bike_type  num_owners      price
0             5      74019        617   scooter           2   74764.69
1             8      73106        352     sport           1   76346.88
2             3      15245        442   scooter           1   91986.42
3            11      30229        202   scooter           1   39996.01
4             2      67788        957  commuter           3  111131.50
...         ...        ...        ...       ...         ...        ...
2495         13      28907        731     sport           2   86795.75
2496          8      48402        819     sport           3  106575.98
2497          9       7598        240     sport           1   80601.70
2498          2      56573        780   scooter           1  101445.67
2499          4      69625        796  commuter           3   95606.05

[2500 rows x 6 columns]

In [2]:
df.shape

(2500, 6)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age_years   2500 non-null   int64
 1   km_driven   2500 non-null   int64
 2   engine_cc   2500 non-null   int64
 3   bike_type   2500 non-null   str
 4   num_owners  2500 non-null   int64
 5   price       2500 non-null   float64
dtypes: float64(1), int64(4), str(1)
memory usage: 134.0 KB

In [4]:
df.describe()

         age_years    km_driven    engine_cc   num_owners          price
count  2500.000000   2500.00000  2500.000000  2500.000000    2500.000000
mean      7.131200  40344.09360   554.710800     1.975200   84095.179264
std       4.322483  22705.33115   260.328939     0.825868   28434.230911
min       0.000000    518.00000   100.000000     1.000000    5061.750000
25%       3.000000  20659.50000   325.750000     1.000000   63808.785000
50%       7.000000  40253.00000   560.000000     2.000000   83836.150000
75%      11.000000  59833.00000   783.250000     3.000000  104377.880000
max      14.000000  79965.00000   999.000000     3.000000  171123.900000

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

age_years     0
km_driven     0
engine_cc     0
bike_type     0
num_owners    0
price         0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['bike_type']=le.fit_transform(df['bike_type'])

In [8]:
## KNN REGRESSION
X=df.drop(['price'],axis=1)
y=df['price']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
## KNN REGRESSOR
from sklearn.neighbors import KNeighborsRegressor
regressor=KNeighborsRegressor()
regressor.fit(X_train,y_train)
y_pred=regressor.predict(X_test)

In [12]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.9523829067091404